name: Run Gradle on PRs
on: 
  pull_request:
    types: [closed]
jobs:
  gradle:
    if: contains(github.head_ref, 'kotlin') && github.base_ref == 'master'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
            ./gradlew build
            ./gradlew generatePomFileForShoweralarmPublication
            ./gradlew publish
      working-directory: kotlin
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
