name: Run Gradle on PRs
on:
  pull_request:
    types: [closed]
jobs:
  gradle:
    if: contains(github.head_ref, 'python') && github.base_ref == 'master'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: pip install -r requirements.txt
        working_directory: python
      - name: Generate GRPC Code
        run: |
          python3 -m grpc_tools.protoc -I ../proto --python_out=. --grpc_python_out=. ../proto/alarmgrpc/alarm.proto
        working_directory: python
      - name: Package
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload --repository-url https://packages.beerfie.com/pypi/ -p "" dist/*
        working_directory: python
        env: TWINE_USERNAME = ${{ secrets.FURY_TOKEN }}
