name: Test & Lint
on: [pull_request]
jobs:
  setup:
    env:
      VAULT_ADDR: https://xxxxxx
      VAULT_SECRETS_FILE: secrets-dev.yml
    runs-on: ubuntu-latest
    steps:
      - name: master
        if: github.ref == 'refs/heads/master'
        run: echo "::set-env name=VAULT_SECRETS_FILE::secrets-prod.yml"
      - name: develop
        if: github.ref == 'refs/heads/develop'
        run: echo "::set-env name=VAULT_SECRETS_FILE::secrets-staging.yml"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://npm.pkg.github.com/
          scope: '@xxxxxx'
      - name: Run secrets
        run: npx -p @xxxxxx/actions-vault-secrets@2.0.2 vault-secrets ${{ env.VAULT_SECRETS_FILE }}
        working-directory: ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          VAULT_ADDR: https://xxxxxx
          AUTH_METHOD: approle
          AUTH_MOUNT_POINT: pipeline
          APPROLE_ROLE_ID: ${{ secrets.ROLE_ID  }}
          APPROLE_SECRET_ID: ${{ secrets.SECRET_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: terraform plan